# Support the author by using the funding links below.
# Developed and maintained by T13nn3s with the help of awesome contributors.
# GitHub Sponsors: https://github.com/sponsors/t13nn3s
# Buy Me a Coffee: https://buymeacoffee.com/t13nn3s

github: T13nn3s
buy_me_a_coffee: t13nn3s

# Sponsoring this project means a lot to me, this will help me to continue building projects like this.
# Wanna get in touch? Check out my bio links: https://binsec.nl/whoami/