#
# Module manifest for module 'DomainHealthChecker'
#
# Generated by: Martien van Dijk
#
# Generated on: 6-7-2021
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'DomainHealthChecker.psm1'

# Version number of this module.
ModuleVersion = '1.5'

# Supported PSEditions
CompatiblePSEditions = @("Desktop")

# ID used to uniquely identify this module
GUID = '9f882a16-ebe1-4e3d-8573-7e014c129d1f'

# Author of this module
Author = 'Martien van Dijk'

# Company or vendor of this module
#CompanyName = ''

# Copyright statement for this module
Copyright = '(c) Martien van Dijk. All rights reserved.'

# Description of the functionality provided by this module
Description = "PowerShell module for checking SPF, DKIM and DMARC-record for one or multiple domains."

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'Invoke-SpfDkimDmarc',
    'Get-SPFRecord',
    'Get-DKIMRecord',
    'Get-DMARCRecord'
    )

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @(
    'Show-SpfDkimDmarc',
    'isdd'
    'gspf'
    'gdkim'
    'gdmarc'
)

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @(
    "CHANGELOG",
    "DomainHealthChecker.psd1",
    "DomainHealthChecker.psm1",
    "LICENSE",
    "README.md"
)

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @("Email", "Emailsecurity", "Security", "SPF", "DKIM", "DMARC")

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/T13nn3s/Show-SpfDkimDmarc/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/T13nn3s/Show-SpfDkimDmarc/'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/T13nn3s/Show-SpfDkimDmarc/main/logo/Show-SpfDkimDmarc.png'

        # ReleaseNotes of this module
        ReleaseNotes = 'https://github.com/T13nn3s/Show-SpfDkimDmarc/blob/main/CHANGELOG'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
HelpInfoURI = 'https://github.com/T13nn3s/Show-SpfDkimDmarc/blob/main/README.md'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

